name: No-Flight-In-PVP
version: '1.0'
main: org.example.noFlightInPVP.NoFlightInPVP
api-version: '1.21'
authors: [ Stilt34, Leviathan ]
description: Disables a players Elytra for a minute when they get hit by another player (PVP).