name: No-Flight-In-PVP
version: '5.0'
main: org.stilt34.noFlightInPVP.NoFlightInPVP
api-version: '1.21'
authors: [ Stilt34, Leviathan ]
description: Disables a players Elytra and Trident for a specified amount of time when they get hit by another player (PVP).